[package]
name = "pthash-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true
lto = "thin"
incremental = true

[dependencies]
bitvec = "1.0.1"
murmur2 = "0.1.0"
rand = "0.8.5"
rustc-hash = "1.1.0"
strength_reduce = "0.2.4"
sucds = "0.8.0"
